site_name: Deep-scan&reg; User Manual

use_directory_urls: false

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Settings: settings.md
  - Troubleshotting: troubleshooting.md
  - About: about.md

markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
      icon: material/toggle-switch
      name: Switch to light mode
      primary: teal
      accent: lime

copyright:
  Copyright &copy; 2024 <a href="www.oremi.sg" target="_blank" rel="nooperner">OREMI AI Pte Ltd, All Rights Reserved</a>